-- Create Resumes table
create table resumes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null default 'My Resume',
  content jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Resumes
alter table resumes enable row level security;

create policy "Users can view their own resumes" on resumes
  for select using (auth.uid() = user_id);

create policy "Users can insert their own resumes" on resumes
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own resumes" on resumes
  for update using (auth.uid() = user_id);

create policy "Users can delete their own resumes" on resumes
  for delete using (auth.uid() = user_id);

-- Create Quizzes table (Admin managed or static for now)
create table quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  questions jsonb not null default '[]'::jsonb, -- Array of {question, options, answer}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Quizzes (Public read, Admin write - for now just public read)
alter table quizzes enable row level security;

create policy "Anyone can view quizzes" on quizzes
  for select using (true);

-- Create Quiz Results table
create table quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  quiz_id bigint references quizzes(id) not null,
  score integer not null,
  total_questions integer not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Quiz Results
alter table quiz_results enable row level security;

create policy "Users can view their own quiz results" on quiz_results
  for select using (auth.uid() = user_id);

create policy "Users can insert their own quiz results" on quiz_results
  for insert with check (auth.uid() = user_id);

-- Create Interview Results table
create table interview_results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  job_role text not null,
  score integer not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Interview Results
alter table interview_results enable row level security;

create policy "Users can view their own interview results" on interview_results
  for select using (auth.uid() = user_id);

create policy "Users can insert their own interview results" on interview_results
  for insert with check (auth.uid() = user_id);
create table resume_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  overall_score integer not null,
  section_scores jsonb not null default '{}'::jsonb,
  feedback text,
  source text default 'quick_analysis', -- 'quick_analysis', 'jd_match', etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Resume Analyses
alter table resume_analyses enable row level security;

create policy "Users can view their own resume analyses" on resume_analyses
  for select using (auth.uid() = user_id);

create policy "Users can insert their own resume analyses" on resume_analyses
  for insert with check (auth.uid() = user_id);
