-- Create the todos table
create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  task text not null,
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table todos enable row level security;

-- Create Policy: Users can view their own todos
create policy "Users can view their own todos" on todos
  for select using (auth.uid() = user_id);

-- Create Policy: Users can insert their own todos
create policy "Users can insert their own todos" on todos
  for insert with check (auth.uid() = user_id);

-- Create Policy: Users can update their own todos
create policy "Users can update their own todos" on todos
  for update using (auth.uid() = user_id);

-- Create Policy: Users can delete their own todos
create policy "Users can delete their own todos" on todos
  for delete using (auth.uid() = user_id);
